### ISSUE TITLE
I can see the list of Categories on the Duty Free Page

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/dutyfree#12]
As an OSS Concourse User when I go to https://concourse.github.io/dutyfree/ I can see the list of categories on the left hand sidebar of the page. 

So that I can can see what categories are available

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ I see the categories on the left hand sidebar of the page.
**And** 
The list of categories includes (List TBC).

PM Notes: List of initial categories to be confirmed by design.

**Comment by carlo-colombo** [comment]
@Pivotal-Kevin-Curley @olwynlee we implemented this story but we did not add any category to the `resources.yml` ( #11 story would add the categories to it ). 

We expect the categories to be added to the `resources.yml` in this way:

```yaml
- name: git resource
  repository: ....
  desc: ....
  categories:
  - git
  - source control
  - concourse
  - trigger
```

We will move this story to the Ready to Accept once the `resources.yml` has been filled in.
